image: python:slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

lint:
  stage: test

  cache:
    paths:
      - .cache/pip
      - .venv/
      - .cache/pre-commit

  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - python --version
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements-dev.txt -U

  script:
    - pre-commit run --all-files
