[tool.pylint.'MASTER']
py-version = "3.10"

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "raw-checker-failed",
  "bad-inline-option",
  "locally-disabled",
  "file-ignored",
  "suppressed-message",
  "useless-suppression",
  "deprecated-pragma",
  "use-symbolic-message-instead",
  "invalid-name",
  "unspecified-encoding", # assume UTF-8
  "line-too-long",
  "too-many-nested-blocks",
  "too-many-branches",
  "duplicate-code",
  "redefined-outer-name",
  "fixme",
  "wrong-import-position"
]

[tool.pylint.'FORMAT']
indent-after-paren = 4
indent-string = "    "
expected-line-ending-format="LF"

[tool.isort]
profile = "black"
