# prevent from being overriden by 100_splunkcloud
[thruput]
maxKBps = 0

[storage_passwords_masking]
view_cleatext_allowlist = 123.123.123.0/24
# https://advisory.splunk.com//advisories/SVD-2026-0707
mask_encr_password = true
