[general]
serverName = splunkhostname
sessionTimeout = 15m

[sslConfig]
enableSplunkdSSL = true
serverCert = /opt/splunk/etc/auth/mycerts/splunk-cert.pem
sslPassword = <private-password-of-splunk-cert.key>
# some distros name it ca-bundle.crt
sslRootCAPath = /etc/ssl/certs/ca-certificates.crt
allowSslCompression = 0
# only applies to tls1.2
cipherSuite = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305
sslVerifyServerCert = 1
sslVerifyServerName = 1
# tls1.3 requires v10.4
sslVersions = tls1.2, tls1.3

# https://help.splunk.com/en/splunk-enterprise/administer/manage-users-and-security/10.4/secure-splunk-platform-communications-with-transport-layer-security-certificates/post-quantum-cryptography-support-in-splunk-enterprise-10.4#configure-splunk-enterprise-to-use-a-pqc-certificate-0
[tls1.3]
# prime256v1 & secp384r1 retained for backward compatibility with OpenSSL 1.0.2 used in UF <=9
groups = X25519MLKEM768, X25519, prime256v1, secp384r1

[pythonSslClientConfig]
sslVerifyServerCert = 1
sslVerifyServerName = 1

[httpServer]
acceptFrom = 127.0.0.1, 123.123.123.0/24

# https://community.splunk.com/t5/Splunk-Enterprise/TailReader-Could-not-send-data-to-output-queue-parsingQueue/m-p/551057/highlight/true#M5766
[queue]
maxSize = 64MB

# override each queue
[queue=fschangemanager_queue]
maxSize = 64MB
[queue=AQ]
maxSize = 64MB
[queue=WEVT]
maxSize = 64MB
[queue=aggQueue]
maxSize = 64MB
[queue=rfsQueue]
maxSize = 64MB
[queue=parsingQueue]
maxSize = 64MB
[queue=remoteOutputQueue]
maxSize = 64MB
[queue=vixQueue]
maxSize = 64MB
