# Disable AI assistant for SPL if not required
# https://help.splunk.com/en/splunk-enterprise/search/search-manual/10.4/use-the-search-app/help-building-searches/use-splunk-ai-assistant-in-the-search-app#ariaid-title3
[feature:search_ai_assistant]
enable_search_ai_assistant = false
